services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/certificates:/app/backend/certificates  # Mount the directory containing ca.pem
    container_name: fastapi-backend
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    container_name: nextjs-frontend
    networks:
      - mynetwork
    command: sh -c "npm install && npm audit fix && npm run dev"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

networks:
  mynetwork:
    driver: bridge
