const vehicleData = [
  {
    id: 1,
    type: 'car',
    manufacturer: 'Tesla',
    model: 'Model S',
    year: 2020,
    price: 49999,
    mileage: 15000,
    condition: 'used',
    city: 'San Francisco',
    state: 'CA',
    photo: 'https://picsum.photos/400/250',
  },

  {
    id: 2,
    type: 'motorcycle',
    manufacturer: 'Yamaha',
    model: 'MT-07',
    year: 2021,
    price: 7499,
    mileage: 5000,
    condition: 'used',
    city: 'Los Angeles',
    state: 'CA',
    engineCapacity: 689,
    bikeType: 'Naked',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 3,
    type: 'truck',
    manufacturer: 'Ford',
    model: 'F-150',
    year: 2021,
    price: 35999,
    mileage: 12000,
    condition: 'used',
    city: 'Dallas',
    state: 'TX',
    cargoCapacity: 1000,
    hasTowingPackage: true,
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 4,
    type: 'truck',
    manufacturer: 'Chevrolet',
    model: 'Silverado',
    year: 2020,
    price: 40999,
    mileage: 15000,
    condition: 'used',
    city: 'Houston',
    state: 'TX',
    cargoCapacity: 1500,
    hasTowingPackage: false,
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 5,
    type: 'car',
    manufacturer: 'Toyota',
    model: 'Camry',
    year: 2019,
    price: 24999,
    mileage: 20000,
    condition: 'certified pre-owned',
    city: 'Phoenix',
    state: 'AZ',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 6,
    type: 'motorcycle',
    manufacturer: 'Harley-Davidson',
    model: 'Street 750',
    year: 2022,
    price: 8999,
    mileage: 3000,
    condition: 'new',
    city: 'Miami',
    state: 'FL',
    engineCapacity: 749,
    bikeType: 'Cruiser',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 7,
    type: 'car',
    manufacturer: 'Honda',
    model: 'Accord',
    year: 2018,
    price: 18999,
    mileage: 35000,
    condition: 'used',
    city: 'Seattle',
    state: 'WA',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 8,
    type: 'truck',
    manufacturer: 'Ram',
    model: '1500',
    year: 2019,
    price: 32999,
    mileage: 18000,
    condition: 'certified pre-owned',
    city: 'Chicago',
    state: 'IL',
    cargoCapacity: 1200,
    hasTowingPackage: true,
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 9,
    type: 'motorcycle',
    manufacturer: 'Kawasaki',
    model: 'Ninja ZX-6R',
    year: 2020,
    price: 10499,
    mileage: 8000,
    condition: 'used',
    city: 'San Diego',
    state: 'CA',
    engineCapacity: 636,
    bikeType: 'Sport',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 10,
    type: 'car',
    manufacturer: 'BMW',
    model: '3 Series',
    year: 2021,
    price: 42999,
    mileage: 10000,
    condition: 'new',
    city: 'New York',
    state: 'NY',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 11,
    type: 'motorcycle',
    manufacturer: 'Ducati',
    model: 'Multistrada V4',
    year: 2022,
    price: 21999,
    mileage: 200,
    condition: 'new',
    city: 'Austin',
    state: 'TX',
    engineCapacity: 1158,
    bikeType: 'Adventure',
    photo: 'https://picsum.photos/400/250',
  },
  {
    id: 12,
    type: 'truck',
    manufacturer: 'GMC',
    model: 'Sierra 2500HD',
    year: 2021,
    price: 47999,
    mileage: 14000,
    condition: 'new',
    city: 'Denver',
    state: 'CO',
    cargoCapacity: 2000,
    hasTowingPackage: true,
    photo: 'https://picsum.photos/400/250',
  },
];

export default vehicleData;
